language: android
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.0
    - android-27
    - sys-img-armeabi-v7a-android-21

# see https://github.com/travis-ci/travis-ci/issues/8874
before_install:
  - yes | sdkmanager "platforms;android-27"

script: ./gradlew clean install --stacktrace && ./gradlew clean build --stacktrace && ./gradlew build | if grep "Failed to find manifest"; then exit 1; else exit 0; fi

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
