dist: trusty
language: android
sudo: false

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - sys-img-armeabi-v7a-android-21
    - extra-google-m2repository
    - extra-android-m2repository

# see https://github.com/travis-ci/travis-ci/issues/8874
before_install:
  - yes | sdkmanager "platforms;android-27"
  - echo y | sdkmanager "cmake;3.6.4111459"
  - echo y | sdkmanager "ndk-bundle"
  - echo y | sdkmanager "lldb;3.1"

  - gem install bundler
  - bundle install

install:
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs

script:
  - ./gradlew clean install --stacktrace
  - ./gradlew clean build --stacktrace
  - bundle exec maze-runner -c

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
